language: node_js
node_js: stable
# S: Build Lifecycle
install:
  - npm install -g yarn
  - yarn
#before_script:
 # - npm install -g gulp
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "luchen"
  - git config user.email "celavue@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
# E: Build LifeCycle
branches:
  only:
    - blog-src
env:
 global:
   - GH_REF: github.com/sisibeloved/hexoBlog.git